---
deployment_name: <deployment_name>
  github:
    test_repo: <githube_repo_url>
    saving_location: <saving_location>
    repo_name: <repo_name>
service:
  name: <service_name>
  port: <port>
  credentials:
    username: <username>
    password: <password>
    certificate: <certificate>
    token: <token>
testing:
  infrastructure: <infrastructure_name>
  tests:
  - name: health
  - name: service
  - name: failover
bosh:
  uaa_url: <uaa_url>
  director_url: <director_url>
  uaa_client: <uaa_client>
  uaa_client_secret: <uua_client_secret>